services:
  - type: web
    name: ai-study-buddy
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: GEMINI_API_KEY_2
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: ai-study-buddy-db
          property: connectionString

databases:
  - name: ai-study-buddy-db
    databaseName: ai_study_buddy
    user: ai_study_buddy
    plan: free
